# Generated by Django 6.0.2 on 2026-02-12 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 9 PM)')], default='evening', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='eco_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
