# Generated by Django 6.0.2 on 2026-02-12 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_daily_login_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('role_applied', models.CharField(choices=[('delivery_partner', 'Delivery Partner'), ('warehouse_associate', 'Warehouse Associate'), ('customer_support', 'Customer Support Executive'), ('sales_executive', 'Sales Executive'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('uiux_designer', 'UI/UX Designer'), ('qa_engineer', 'QA Engineer'), ('digital_marketing', 'Digital Marketing Specialist'), ('operations_manager', 'Operations Manager')], max_length=50)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('resume_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
