# Generated by Django 6.0.2 on 2026-02-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
