# Generated by Django 6.0.1 on 2026-02-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacturing Date'),
        ),
    ]
