# Generated by Django 6.0.2 on 2026-03-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_expiry_date_product_mfg_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='role_applied',
            field=models.CharField(choices=[('delivery_partner', 'Delivery Partner'), ('merchant_partner', 'Merchant Partner'), ('warehouse_associate', 'Warehouse Associate'), ('customer_support', 'Customer Support Executive'), ('sales_executive', 'Sales Executive'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('uiux_designer', 'UI/UX Designer'), ('qa_engineer', 'QA Engineer'), ('digital_marketing', 'Digital Marketing Specialist'), ('operations_manager', 'Operations Manager')], max_length=50),
        ),
    ]
