# Generated by Django 6.0.1 on 2026-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_seller_alter_jobapplication_role_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
