# Generated by Django 6.0.1 on 2026-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_jobapplication_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store_status',
            field=models.BooleanField(default=False),
        ),
    ]
