# Generated by Django 6.0.2 on 2026-04-28 13:05

from datetime import timedelta

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_merchant_subscription_plans(apps, schema_editor):
    MerchantSubscriptionPlan = apps.get_model("api", "MerchantSubscriptionPlan")
    plans = [
        {
            "code": "starter",
            "name": "Starter",
            "short_description": "Best for new merchants launching a focused catalogue.",
            "monthly_price": "499.00",
            "yearly_price": "4990.00",
            "product_limit": 25,
            "commission_rate": "8.50",
            "priority_support": False,
            "advanced_analytics": True,
            "featured_placement": False,
            "is_recommended": False,
            "is_active": True,
            "sort_order": 1,
        },
        {
            "code": "growth",
            "name": "Growth",
            "short_description": "For growing stores that need more listings and support.",
            "monthly_price": "1499.00",
            "yearly_price": "14990.00",
            "product_limit": 150,
            "commission_rate": "6.00",
            "priority_support": True,
            "advanced_analytics": True,
            "featured_placement": True,
            "is_recommended": True,
            "is_active": True,
            "sort_order": 2,
        },
        {
            "code": "scale",
            "name": "Scale",
            "short_description": "Unlimited listings for high-volume merchants on Paras Traders.",
            "monthly_price": "2999.00",
            "yearly_price": "29990.00",
            "product_limit": None,
            "commission_rate": "4.50",
            "priority_support": True,
            "advanced_analytics": True,
            "featured_placement": True,
            "is_recommended": False,
            "is_active": True,
            "sort_order": 3,
        },
    ]
    for plan in plans:
        MerchantSubscriptionPlan.objects.get_or_create(
            code=plan["code"],
            defaults=plan,
        )


def backfill_existing_merchant_subscriptions(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    MerchantSubscriptionPlan = apps.get_model("api", "MerchantSubscriptionPlan")
    MerchantSubscription = apps.get_model("api", "MerchantSubscription")

    default_plan = (
        MerchantSubscriptionPlan.objects.filter(code="starter").order_by("id").first()
        or MerchantSubscriptionPlan.objects.order_by("sort_order", "id").first()
    )
    if not default_plan:
        return

    now = timezone.now()
    merchant_ids = UserProfile.objects.filter(
        employee_role="merchant_partner"
    ).values_list("user_id", flat=True)

    for merchant_id in merchant_ids:
        if MerchantSubscription.objects.filter(merchant_id=merchant_id).exists():
            continue
        MerchantSubscription.objects.create(
            merchant_id=merchant_id,
            plan_id=default_plan.id,
            billing_cycle="monthly",
            status="active",
            amount=default_plan.monthly_price,
            starts_at=now,
            ends_at=now + timedelta(days=30),
            activated_at=now,
            auto_renew=True,
            notes="Grandfathered existing merchant during subscription rollout",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_support', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=True)),
                ('featured_placement', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price', 'id'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='api.merchantsubscriptionplan'),
        ),
        migrations.CreateModel(
            name='MerchantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.merchantsubscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='api_msub_user_stat_idx'), models.Index(fields=['ends_at'], name='api_msub_end_idx')],
            },
        ),
        migrations.RunPython(
            seed_merchant_subscription_plans,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_existing_merchant_subscriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
